name: Publish package

on:
  push:
    tags: v*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build
        run: wasm-pack build --release --target=web
      # - run: wasm-pack pack
      - name: Publish
        working-directory: pkg
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://npm.pkg.github.com/etsune" >> .npmrc
          echo "@etsune:registry=https://npm.pkg.github.com" >> .npmrc
          npm publish --access=public
